# Name of the workflow (appears in GitHub Actions UI)
name: 07-Environment-Variable-scope

# Defines when this workflow should run
on:
  workflow_dispatch:
    # Trigger when code is pushed
env:
    WORKFLOW_VAR: I_AM_WORKFLOW_SCOPED

jobs:
    job-1:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: IAM_JOB_SCOPED
        steps:
         - name: Inspect scopes job 1 step 1
           env:
            STEP1_VAR1: IAM_STEP_SCOPED
           run: |
             echo "Workflow_VAR: $WORKFLOW_VAR"
             echo "JOB_VAR: $JOB_VAR"
             echo "STEP1_VAR1: $STEP_VAR1"
            
         - name: Inspect scopes job 1 step 2
           env:
            STEP2_VAR2: IAM_SECOND_STEP_SCOPED
           run: |
             echo "Workflow_VAR: $WORKFLOW_VAR"
             echo "JOB_VAR: $JOB_VAR"
             echo "STEP1_VAR1: $STEP1_VAR1"
             echo "STEP2_VAR2: $STEP2_VAR2"
    job-2:
        runs-on: ubuntu-latest
        steps:
         - name: Inspect scopes job 2 step 2
           run: |
             echo "Workflow_VAR: $WORKFLOW_VAR"
             echo "JOB_VAR: $JOB_VAR"
             echo "STEP1_VAR1: $STEP1_VAR1"
             echo "STEP2_VAR2: $STEP2_VAR2"